var quotes = 
[
	{"quote": "Love looks through a telescope; envy, through a microscope.", "author": "Josh Billings"},
	{"quote": "There can be no deep disappointment where there is not deep love.", "author": "Martin Luther King Jr."},
	{"quote": "Nothing is miserable unless you think it is so.", "author": "Boethius"},
	{"quote": "When you're in love you never really know whether your elation comes from the qualities of the one you love, or if it attributes them to her; whether the light which surrounds her like a halo comes from you, from her, or from the meeting of your sparks.", "author": "Natalie Clifford Barney"},
	{"quote": "Those who are faithful know only the trivial side of love: it is the faithless who know love's tragedies.", "author": "Oscar Wilde"},
	{"quote": "I think it is all a matter of love the more you love a memory, the stronger and stranger it is.", "author": "Vladimir Nabokov"},
	{"quote": "Love won't be tampered with, love won't go away. Push it to one side and it creeps to the other.", "author": "Isak Dinesen"},
	{"quote": "Love is the magician that pulls man out of his own hat.", "author": "Ben Hecht"},
	{"quote": "But whether it be dream or truth, to do well is what matters. If it be truth, for truth's sake. If not, then to gain friends for the time when we awaken.", "author": "Pedro Calderon de la Barca"},
	{"quote": "If thou rememb'rest not the slightest folly into which love hast made thee run, though hast not loved.", "author": "William Shakespeare"},
	{"quote": "Getting divorced just because you don't love a man is almost as silly as getting married just because you do.", "author": "Zsa Zsa Gabor"},
	{"quote": "Love is a gross exaggeration of the difference between one person and everybody else.", "author": "George Bernard Shaw"},
	{"quote": "If music be the food of love, play on.", "author": "William Shakespeare"},
	{"quote": "In love of home, the love of country has its rise.", "author": "Charles Dickens"},
	{"quote": "I met in the street a very poor young man who was in love. His hat was old, his coat worn, his cloak was out at the elbows, the water passed through his shoes -- and the stars through his soul.", "author": "Victor Hugo"},
	{"quote": "Stand by your man. Give him two arms to cling to and something warm to come to.", "author": "Tammy Wynette"},
	{"quote": "Love is the triumph of imagination over intelligence.", "author": "Henry Mencken"},
	{"quote": "Love is the word used to label the sexual excitement of the young, the habituation of the middle-aged, and the mutual dependence of the old.", "author": "John Ciardi"},
	{"quote": "In true love the smallest distance is too great, and the greatest distance can be bridged.", "author": "Hans Nouwens"},
	{"quote": "The magic of first love is our ignorance that it can never end.", "author": "Benjamin Disraeli"},
	{"quote": "Why love if losing hurts so much We love to know that we are not alone.", "author": "Clive Staples Lewis"},
	{"quote": "Hallow the body as a temple to comeliness and sanctify the heart as a sacrifice to love; love recompenses the adorers.", "author": "Kahlil Gibran"},
	{"quote": "Love is composed of a single soul inhabiting two bodies.", "author": "Aristotle"},
	{"quote": "Three grand essentials to happiness in this life are something to do, something to love, and something to hope for.", "author": "Joseph Addison"},
	{"quote": "There is more hunger in the world for love and appreciation than for bread.", "author": "Mother Teresa"},
	{"quote": "No human relation gives one possession in another...every two souls are absolutely different. In friendship and in love, the two side by side raise hands together to find what one cannot reach alone.", "author": "Kahlil Gibran"},
	{"quote": "Love yourself first and everything else falls into line. You really have to love yourself to get anything done in this world.", "author": "Lucille Ball"},
	{"quote": "A man in love is incomplete until he has married. Then he's finished.", "author": "Zsa Zsa Gabor"},
	{"quote": "Neither a lofty degree of intelligence nor imagination nor both together go to the making of genius. Love, love, love, that is the soul of genius.", "author": "Wolfgang Amadeus Mozart"},
	{"quote": "Life is but a brief moment. The years go by quickly and old age arrives suddenly before we have an inkling. People desire so many things and waste their days in vain. Some yearn for gold, others for power, yet others for glory and a higher station. But when death's moment nears and they look back at their lives they've lived, they realise they've been happy only during those moments when they've loved.", "author": "Borje Vahamaki"},
	{"quote": "If you judge people, you have no time to love them.", "author": "Mother Teresa"},
	{"quote": "Love conquers all things let us too surrender to Love.", "author": "Virgil"},
	{"quote": "Love is like war: easy to begin but very hard to stop.", "author": "Henry Mencken"},
	{"quote": "To love abundantly is to live abundantly, and to love forever is to live forever.", "author": "Henry Drummond"},
	{"quote": "Love is the extra effort we make in our dealings with those whom we do not like and once you understand that, you understand all. This idea that love overtakes you is nonsense. This is but a polite manifestation of sex. To love another you have to undertake some fragment of their destiny.", "author": "Pierre Corneille"},
	{"quote": "If Jack's in love, he's no judge of Jill's beauty.", "author": "Benjamin Franklin"},
	{"quote": "There is hardly any activity, any enterprise, which is started out with such tremendous hopes and expectations, and yet which fails so regularly, as love.", "author": "Erich Fromm"},
	{"quote": "Civilized people need love for full sexual satisfaction.", "author": "Author Unknown"},
	{"quote": "Love anything and your heart will be wrung and possibly broken. If you want to make sure of keeping it intact you must give it to no one, not even an animal. Wrap it carefully round with hobbies and little luxuries; avoid all entanglements. Lock it up safe in the casket or coffin of your selfishness. But in that casket, safe, dark, motionless, airless, it will change. It will not be broken; it will become unbreakable, impenetrable, irredeemable. To love is to be vulnerable.", "author": "C.S. Lewis"},
	{"quote": "The art of love is largely the art of persistence.", "author": "Albert Ellis"},
	{"quote": "Intense love does not measure, it just gives.", "author": "Mother Teresa"},
	{"quote": "He who loves 50 people has 50 woes; he who loves no one has no woes.", "author": "Siddhartha Buddha"},
	{"quote": "And what’s romance? Usually, a nice little tale where you have everything As You Like It, where rain never wets your jacket and gnats never bite your nose and it’s always daisy-time.", "author": "D.H. Lawrence"},
	{"quote": "All thoughts, all passions, all delights Whatever stirs this mortal frame All are but ministers of Love And feed His sacred flame.", "author": "Charles Caleb Colton"},
	{"quote": "Love is a canvas furnished by nature and embroidered by imagination.", "author": "Francois Marie Arouet (Voltaire)"},
	{"quote": "A mighty pain to love it is, and 'tis a pain that pain to miss but of all the pains, the greatest pain is to love, but love in vain.", "author": "Abraham Crowley"},
	{"quote": "To write a good love letter, you ought to begin without knowing what you mean to say and to finish without knowing what you have written.", "author": "Jean-Jacques Rousseau"},
	{"quote": "I dont think anyone can DO anything that would make him worthy of love. Love is a gift and cannot be earned. It can only be given.", "author": "Real Live Preacher"},
	{"quote": "God is Love -- I dare say. But what a mischievous devil Love is", "author": "Samuel Butler"},
	{"quote": "Love is agrowing, to full constant light; and his first minute, after noon, is night.", "author": "John Donne"},
	{"quote": "Love means having to say you're sorry every fifteen minutes.", "author": "John Lennon"},
	{"quote": "Looking back, I have this to regret, that too often when I loved, I did not say so.", "author": "David Grayson"},
	{"quote": "Love's always a little lonely in the beginning.", "author": "Douglas Sirk"},
	{"quote": "I think it is all a matter of love: the more you love a memory, the stronger and stranger it is.", "author": "Rotarian"},
	{"quote": "Sometimes it's a form of love just to talk to somebody that you have nothing in common with and still be fascinated by their presence.", "author": "David Byrne"},
	{"quote": "Love endures only when the lovers love many things together and not merely each other.", "author": "Walter Lippmann"},
	{"quote": "Clarity of mind means clarity of passion, too; this is why a great and clear mind loves ardently and sees distinctly what it loves.", "author": "Blaise Pascal"},
	{"quote": "Love is the delightful interval between meeting a beautiful girl and discovering that she looks like a haddock.", "author": "John Barrymore"},
	{"quote": "Life in abundance comes only through great love.", "author": "Elbert Hubbard"},
	{"quote": "A cat does not want all the world to love her -- only those she has chosen to love.", "author": "Helen Thomson"},
	{"quote": "Like everybody who is not in love, he thought one chose the person to be loved after endless deliberations and on the basis of particular qualities or advantages.", "author": "Marcel Proust"},
	{"quote": "Loving people live in a loving world. Hostile people live in a hostile world.", "author": "Wayne Dyer"},
	{"quote": "Love is a verb.", "author": "Author Unknown"},
	{"quote": "A loving heart is the beginning of all knowledge.", "author": "Thomas Carlyle"},
	{"quote": "Immature love says 'I love you because I need you.' Mature love says 'I need you because I love you.'", "author": "Erich Fromm"},
	{"quote": "Love is like quicksilver in the hand. Leave the fingers open and it stays. Clutch it, and it darts away.", "author": "Dorothy Parker"},
	{"quote": "Love means not ever having to say you're sorry.", "author": "Erich Segal"},
	{"quote": "Our hours in love have wings; in absence, crutches.", "author": "Colley Cibber"},
	{"quote": "A man content to go to heaven alone will never go to heaven.", "author": "Boethius"},
	{"quote": "Loving is not just looking at each other, it's looking in the same direction.", "author": "Antoine de Saint-Exupery"},
	{"quote": "A relationship is like a rose, How long it lasts, no one knows Love can erase an awful past, Love can be yours, you'll see at last To feel that love, it makes you sigh, To have it leave, you'd rather die You hope you've found that special rose, 'Cause you love and care for the one you chose.", "author": "Rob Cella"},
	{"quote": "Love is like war: easy to begin but very hard to stop.", "author": "H. L. Mencken"},
	{"quote": "Love is not affectionate feeling, but a steady wish for the loved person's ultimate good as far as it can be obtained.", "author": "C.S. Lewis"},
	{"quote": "Love is a flame that burns in heaven, And whose soft reflections radiate to us. Two worlds are opened, two lives given to it. It is by love tht we double our being It is by love that we approach God.", "author": "Aimee Martin"},
	{"quote": "To love another person is to help them love God.", "author": "Sren Aaby Kierkegaard"},
	{"quote": "Say what you will, 'tis better to be left than never to have been loved.", "author": "William Congreve"},
	{"quote": "I have found the paradox, that if you love until it hurts, there can be no more hurt, only more love.", "author": "Mother Teresa"},
	{"quote": "Love is the flower you've got to let grow.", "author": "John Lennon"},
	{"quote": "The laws of gravity cannot be held responsible for people falling in love.", "author": "Albert Einstein"},
	{"quote": "Love is, above all, the gift of oneself.", "author": "Bertrand Russell"},
	{"quote": "We need not think alike to love alike.", "author": "Francis David"},
	{"quote": "As soon go kindle fire with snow, as seek to quench the fire of love with words.", "author": "William Shakespeare"},
	{"quote": "I love her and she loves me, and we hate each other with a wild hatred born of love.", "author": "August Strindberg"},
	{"quote": "I was about half in love with her by the time we sat down. That's the thing about girls. Every time they do something pretty... you fall half in love with them, and then you never know where the hell you are.", "author": "J. D. Salinger"},
	{"quote": "Love is energy of life.", "author": "Robert Browning"},
	{"quote": "Love built on beauty, soon as beauty, dies.", "author": "John Donne"},
	{"quote": "In his younger days a man dreams of possessing the heart of the woman whom he loves; later, the feeling that he possesses the heart of a woman may be enough to make him fall in love with her.", "author": "Marcel Proust"},
	{"quote": "Lat: Love me faithfully!/See how I am faithful:/With all my heart/And all my soul/I am with you/Though I am far away.", "author": "Anon."},
	{"quote": "The hardest of all is learning to be a well of affection, and not a fountain; to show them we love them not when we feel like it, but when they do.", "author": "Nan Fairbrother"},
	{"quote": "What a profound significance small things assume when the woman we love conceals them from us.", "author": "Marcel Proust"},
	{"quote": "Love came down at Christmas Love all lovely, love divine Love was born at Christmas, Stars and angels gave the sign.", "author": "Christina Georgina Rossetti"},
	{"quote": "Love that is not madness is not love.", "author": "Pedro Calderon de la Barca"},
	{"quote": "The Bible tells us to love our neighbors, and also to love our enemies probably because they are generally the same people.", "author": "G. K. Chesterton"},
	{"quote": "To enlarge or illustrate this power and effect of love is to set a candle in the sun.", "author": "Robert Burton"},
	{"quote": "I never knew how to worship until I knew how to love.", "author": "Henry Ward Beecher"},
	{"quote": "To love is not a passive thing. To love is active voice. When I love I do something, I function, I give. I do not love in order that I may be loved back again, but for the creative joy of loving. And every time I do so love I am freed, at least a little, by the outgoing of love, from enslavement to that most intolerable of master, myself.", "author": "Bernard Iddings Bell"},
	{"quote": "Only love interests me, and I am only in contact with things that revolve around love.", "author": "Marc Chagall"},
	{"quote": "Time is too slow for those who wait, too swift for those who fear, too long for those who grieve, too short for those who rejoice, but for those who love, time is eternity.", "author": "Henry Van Dyke"},
	{"quote": "Love is not something that you can put chains on and throw into a lake. That's called Houdini. Love is liking someone a lot.", "author": "Jack Handey Deep Thoughts"},
	{"quote": "The music business was not safe, but it was FUN. It was like falling in love with a woman you know is bad for you, but you love every minute with her, anyway.", "author": "Lionel Richie"},
	{"quote": "Life is one fool thing after another where as love is two fool things after each other.", "author": "Oscar Wilde"},
	{"quote": "To be wise and love exceeds man's might.", "author": "William Shakespeare"},
	{"quote": "Hallow the body as a temple to comeliness and sanctify the heart as a sacrifice to love love recompenses the adorers.", "author": "Kahlil Gibran"},
	{"quote": "I can think of no better way of redeeming this tragic world today than love and laughter. Too many of the young have forgotten how to laugh, and too many of the elders have forgotten how to love. Would not our lives be lightened if only we could all learn to laugh more easily at ourselves and to love one another", "author": "Theodore Hesburgh"},
	{"quote": "If we discovered that we only had five minutes left to say all that we wanted to say, every telephone booth would be occupied by people calling other people to stammer that they loved them.", "author": "Christopher Morley"},
	{"quote": "He fell in love with himself at first sight, and it is a passion to which he has always remained faithful. Self-love seems so often unrequited.", "author": "Anthony Powell"},
	{"quote": "Where love rules, there is no will to power; and where power predominates, there love is lacking. The one is the shadow of the other.", "author": "Carl Jung"},
	{"quote": "If you want to be loved, be lovable.", "author": "Ovid"},
	{"quote": "Love is my religion - I could die for it.", "author": "John Keats"},
	{"quote": "Who would give a law to lovers? Love is unto itself a higher law.", "author": "Boethius"},
	{"quote": "To love and win is the best thing. To love and lose, the next best.", "author": "William Makepeace Thackeray"},
	{"quote": "True love is like ghosts, which everyone talks about and few have seen.", "author": "Francois de La Rochefoucauld"},
	{"quote": "Time is too slow for those who wait, too swift for those who fear, too long for those who grieve, too short for those who rejoice, but for those who love, time is eternity.", "author": "Henry Van Dyke"},
	{"quote": "Love doesn't make the world go round. Love makes the ride worthwhile.", "author": "Franklin Jones"},
	{"quote": "Feedom has never been free ... I love my children and I love my wife with all my heart. And I would die, die gladly, if that would make a better life for them.", "author": "Medgar Evers"},
	{"quote": "The giving of love is an education in itself.", "author": "Eleanor Roosevelt"},
	{"quote": "They say love is around every corner. I must be walking in circles.", "author": "Author Unknown"},
	{"quote": "We are not the same persons this year as last nor are those we love. It is a happy chance if we, changing, continue to love a changed person.", "author": "Jacques Maritain"},
	{"quote": "Once when I was young and true, Someone left me sad- Broke my brittle heart in two; And that was very bad. Love is for unlucky folk. Love is but a curse. Once there was a heart I broke; And that, I think, is worse.", "author": "La Rochefoucauld"},
	{"quote": "Love is friendship set on fire.", "author": "Jeremy Taylor"},
	{"quote": "In a separation it is the one who is not really in love who says the more tender things.", "author": "Marcel Proust"},
	{"quote": "Whoso loves believes the impossible.", "author": "Elizabeth Barrett Browning"},
	{"quote": "We cannot all do great things, but we can do small things with great love.", "author": "Mother Teresa"},
	{"quote": "To love and win is the best thing, to love and lose, the next best.", "author": "William Makepeace Thackeray"},
	{"quote": "Those who never retract their opinions love themselves more than they love the truth.", "author": "Jeseph Joubert"},
	{"quote": "Love takes up where knowledge leaves off.", "author": "Thomas Aquinas"},
	{"quote": "A baby is born with a need to be loved - and never outgrows it.", "author": "Frank A. Clark"},
	{"quote": "Absence sharpens love, presence strengthens it.", "author": "Benjamin Franklin"},
	{"quote": "Love is the self-delusion we manufacture to justify the trouble we take to have sex.", "author": "Daniel S. Greenberg"},
	{"quote": "Love all love of other sights controls, And makes one little room an everywhere.", "author": "John Donne"},
	{"quote": "A coward is incapable of exhibiting love; it is the prerogative of the brave.", "author": "Mahatma Gandhi"},
	{"quote": "Footfalls echo in the memory, down the passage which we did not take, towards the door we never opened Into the rose-garden.", "author": "T. S. Eliot"},
	{"quote": "We are shaped and fashioned by what [whom] we love.", "author": "Helen Hayes"},
	{"quote": "Love doesn't make the world go round. Love is what makes the ride worthwhile.", "author": "Franklin P. Jones"},
	{"quote": "Fortune and love favor the brave.", "author": "Ovid"},
	{"quote": "Love seeks one thing only the good of the one loved. It leaves all the other secondary effects to take care of themselves. Love, therefore, is its own reward.", "author": "Thomas Merton"},
	{"quote": "To give and not expect return, that is what lies at the heart of love.", "author": "Oscar Wilde"},
	{"quote": "There is only one terminal dignity - love.", "author": "Helen Hayes"},
	{"quote": "How did it happen that their lips came together? How does it happen that birds sing, that snow melts, that the rose unfolds, that the dawn whitens behind the stark shapes of trees on the quivering summit of the hill? A kiss, and all was said.", "author": "Victor Hugo"},
	{"quote": "It is sad not to love, but it is much sadder not to be able to love.", "author": "Miguel de Unamuno"},
	{"quote": "When you're comfortable with someone you love, the silence is the best.", "author": "Britney Spears"},
	{"quote": "I love to go shopping. I love to freak out salespeople. They ask me if they can help me, and I say, \"Have you got anything I'd like?\"Then they ask me what size I need, and I say, \"Extra medium.\"", "author": "Steven Wright"},
	{"quote": "I love my past. I love my present. I'm not ashamed of what I've had, and I'm not sad because I have it no longer.", "author": "Sidonie Gabrielle Colette"},
	{"quote": "If you press me to say why I loved him, I can say no more than because he was he, and I was I.", "author": "Michel de Montaigne"},
	{"quote": "If you cannot inspire a woman with love of you, fill her above the brim with love of herself; all that runs over will be yours.", "author": "Charles Caleb Colton"},
	{"quote": "Love does not begin and end the way we seem to think it does. Love is a battle, love is a war love is a growing up.", "author": "James Baldwin"},
	{"quote": "I like not only to be loved, but to be told I am loved.", "author": "George Eliot"},
	{"quote": "Could you imagine how horrible things would be if we always told others how we felt? Life would be intolerably bearable.", "author": "Randy K. Milholland"},
	{"quote": "Where there is no exaggeration there is no love, and where there is no love there is no understanding.", "author": "Oscar Wilde"},
	{"quote": "When he spoke, what tender words he used! So softly, that like flakes of feathered snow, They melted as they fell.", "author": "John Dryden"},
	{"quote": "Parents must get across the idea that I love you always, but sometimes I do not love your behavior.", "author": "Amy Vanderbilt"},
	{"quote": "You are what you love. Not what loves you.", "author": "Charlie Kaufman"},
	{"quote": "We waste time looking for the perfect lover, instead of creating the perfect love.", "author": "Tom Robbins"},
	{"quote": "The love of one's country is a splendid thing. But why should love stop at the border?", "author": "Pablo Casals"},
	{"quote": "And, oh, how blessed is it thus to meet! To feel that vanished years have not estranged us, distance has not diminished love, that we are to each other even as we parted; to feel again the fond kiss, to hear once more the accents of a voice which to us h", "author": "Abu Hamid Al-Ghazzali"},
	{"quote": "One advantage of marriage, it seems to me, is that when you fall out of love with him, or he falls out of love with you, it keeps you together until you maybe fall in love again.", "author": "Judith Viorst"},
	{"quote": "That's the nature of women not to love when we love them, and to love when we love them not.", "author": "Miguel de Cervantes"},
	{"quote": "Love many things, for therein lies the true strength, and whosoever loves much performs much, and can accomplish much, and what is done in love is done well.", "author": "Vincent Van Gogh"},
	{"quote": "Love is or it ain't. Thin love ain't love at all.", "author": "Toni Morrison"},
	{"quote": "Love is a promise, love is a souvenir, once given never forgotten, never let it disappear.", "author": "John Lennon"},
	{"quote": "Footfalls echo in the memory Down the passage which we did not take Towards the door we never opened Into the rose-garden. My words echo Thus, in your mind.", "author": "Ralph Waldo Emerson"},
	{"quote": "First love is only a little foolishness and a lot of curiosity.", "author": "George Bernard Shaw"},
	{"quote": "Not where I breathe, but where I love, I live Not where I love, but where I am, I die.", "author": "Robert Southey"},
	{"quote": "Before I met my husband, I'd never fallen in love. I'd stepped in it a few times.", "author": "Rita Rudner"},
	{"quote": "All doubt, despair, and fear become insignificant once the intention of life becomes love, rather than dependence on love.", "author": "Sri da Avabhas"},
	{"quote": "It's strange that words are so inadequate. Yet, like the asthmatic struggling for breath, so the lover must struggle for words.", "author": "T.S. Eliot"},
	{"quote": "Whatever our souls are made of, his and mine are the same.", "author": "Emily Bronte"},
	{"quote": "You can't love anyone until you understand that you can't love everyone.", "author": "Real Live Preacher"},
	{"quote": "Love is that splendid triggering of human vitality the supreme activity which nature affords anyone for going out of himself toward someone else.", "author": "Jose Ortega y Gasset"},
	{"quote": "For a mother is the only person on earth Who can divide her love among ten children And each child still have all her love.", "author": "Anon."},
	{"quote": "The simple lack of her is more to me than others' presence.", "author": "Edward Thomas"},
	{"quote": "If, as I can't help suspecting, the dead also feel the pains of separation (and this may be one of their purgatorial sufferings), then for both lovers, and for all pairs of lovers without exception, bereavement is a universal and integral part of our experience of love.", "author": "C.S. Lewis"},
	{"quote": "Love is like an hourglass, with the heart filling up as the brain empties.", "author": "Jules Renard"},
	{"quote": "Neither a lofty degree of intelligence nor imagination nor both together go to the making of genius. Love, love, love, that is the soul of genius.", "author": "Wolfgang Amadeus Mozart"},
	{"quote": "Age does not protect you from love, but love to some extent protects you from age.", "author": "Jeanne Moreau"},
	{"quote": "How on earth are you ever going to explain in terms of chemistry and physics so important a biological phenomenon as first love?", "author": "Albert Einstein"},
	{"quote": "We loved with a love that was more than love.", "author": "Edgar Allan Poe"},
	{"quote": "Love is needing to be loved.", "author": "John Lennon"},
	{"quote": "Love is not love that alters when it alteration finds.", "author": "William Shakespeare"},
	{"quote": "If you would be loved, love and be lovable.", "author": "Benjamin Franklin"},
	{"quote": "For the memory of love is sweet, though the love itself were in vain. And what I have lost of pleasure, assuage what I find of pain.", "author": "Lyster"},
	{"quote": "The love we give away is the only love we keep.", "author": "Elbert Hubbard"},
	{"quote": "I know of only one duty, and that is to love.", "author": "George Bernard Shaw"},
	{"quote": "Love is an attachment to another self. Humor is a form of self-detachment -- a way of looking at one's existence, one's misfortune, or one's discomfort. If you really love, if you really know how to laugh, the result is the same you forget yourself.", "author": "Claude Roy"},
	{"quote": "Music makes one feel so romantic - at least it always gets on one's nerves - which is the same thing nowadays.", "author": "Oscar Wilde"},
	{"quote": "Money can't buy love, but it improves your bargaining position.", "author": "Christopher Marlowe"},
	{"quote": "It is impossible to love and to be wise.", "author": "Francis Bacon"},
	{"quote": "If there is a God, whence proceed so many evils? If there is no God, whence cometh any good?", "author": "Boethius"},
	{"quote": "Come live with me, and be my love, And we will some new pleasures prove, Of golden sands, and crystal brooks, With silken lines, and silver hooks.", "author": "John Donne"},
	{"quote": "Love is something far more than desire for sexual intercourse; it is the principal means of escape from the loneliness which afflicts most men and women throughout the greater part of their lives.", "author": "Bertrand Russell"},
	{"quote": "Love is metaphysical gravity.", "author": "R. Buckminster Fuller"},
	{"quote": "The odds of not meeting in this life are so great that every meeting is like a miracle. It's a wonder that we don't make love to every single person we meet.", "author": "Yoko Ono"},
	{"quote": "The love of liberty is the love of others the love of power is the love of ourselves.", "author": "William Hazlitt"},
	{"quote": "Take my hand And lead me to salvation Take my love For love is everlasting And remember The truth that once was spoken To love another person Is to see the face of God.", "author": "Jean Valjean"},
	{"quote": "All love shifts and changes. I don't know if you can be wholeheartedly in love all the time.", "author": "Julie Andrews"},
	{"quote": "Love therefore??”the most beautiful phenomenon in the soul-filled creation, the omnipotent magnet in the spiritual world, the source of devotion and of the most sublime virtue??”Love is only the reflection of this single original power, an attraction of the e", "author": "Percy Bysshe Shelley"},
	{"quote": "He loves but little who can say and count in words how much he loves.", "author": "Dante Alighieri"},
	{"quote": "An act of love that fails is just as much a part of the divine life as an act of love that succeeds, for love is measured by fullness, not by reception.", "author": "Harold Loukes"},
	{"quote": "Why be something to everybody when you can be everything to somebody?", "author": "GK Chesterton"},
	{"quote": "Love means loving the unlovable - or it is no virtue at all.", "author": "GK Chesterton"},
	{"quote": "To love means to commit oneself without guarantee, to give oneself completely in the hope that our love will produce love in the loved person.", "author": "Erich Fromm"},
	{"quote": "Love never dies a natural death. It dies because we don't know how to replenish it's source. It dies of blindness and errors and betrayals. It dies of illness and wounds; it dies of weariness, of witherings, of tarnishings.", "author": "Anais Nin"},
	{"quote": "For in all adversity of fortune the worst sort of misery is to have been happy.", "author": "Boethius"},
	{"quote": "That is the true season of love, when we believe that we alone can love, that no one could ever have loved so before us, and that no one will love in the same way after us.", "author": "Johann Wolfgang von Goethe"},
	{"quote": "Love is the wisdom of the fool and the folly of the wise.", "author": "Samuel Johnson"},
	{"quote": "Sympathy constitutes friendship; but in love there is a sort of antipathy, or opposing passion. Each strives to be the other, and both together make up one whole.", "author": "Samuel Taylor Coleridge"},
	{"quote": "The way to love anything is to realize that it may be lost.", "author": "Gilbert K. Chesterton"},
	{"quote": "Who dares deny that this is true: The whole is more than all its parts? A whole love than divided love, Or than half love from fifty hearts? Yet who dare either this deny: The part is more than is the whole? That treasures halved with one dear love", "author": "John Donne"},
	{"quote": "Love is only a dirty trick played on us to achieve continuation of the species.", "author": "W. Somerset Maugham"},
	{"quote": "It is easier to love humanity as a whole than to love one's neighbor.", "author": "Eric Hoffer"},
	{"quote": "If you wish to be loved, show more of your faults than your virtues.", "author": "Edward Bulwer-Lytton"},
	{"quote": "Love seems the swiftest, but it is the slowest of all growths. No man or woman really knows what perfect love is until they have been married a quarter of a century.", "author": "Mark Twain"},
	{"quote": "Love is the idler's occupation, the warrior's relaxation, and the soverign's ruination.", "author": "Napoleon Bonaparte"},
	{"quote": "About all you can do in life is be who you are. Some people will love you for you. Most will love you for what you can do for them, and some won't like you at all.", "author": "Rita Mae Brown"},
	{"quote": "We are not the same persons this year as last; nor are those we love. It is a happy chance if we, changing, continue to love a changed person.", "author": "W. Somerset Maugham"},
	{"quote": "What else is love but understanding and rejoicing in the fact that another person lives, acts, and experiences otherwise than we do????", "author": "Friedrich Nietzsche"},
	{"quote": "If you love somebody, let them go, for if they return, they were always yours. And if they don't, they never were.", "author": "Kahlil Gibran"},
	{"quote": "Love is a game that two can play and both win.", "author": "Eva Gabor"},
	{"quote": "You can't buy love, but you can pay heavily for it.", "author": "Henny Youngman"},
	{"quote": "Today I begin to understand what love must be, if it exists. When we are parted, we each feel the lack of the other half of ourselves. We are incomplete like a book in two volumes of which the first has been lost. That is what I imagine love to be: incompleteness in absence.", "author": "Edmond and Jules de Goncourt"},
	{"quote": "The essence of romantic love is not the company of a lover but the pursuit.", "author": "Andrew Sullivan"},
	{"quote": "Everybody can be great... because anybody can serve. You don't have to have a college degree to serve. You don't have to make your subject and verb agree to serve. You only need a heart full of grace. A soul generated by love.", "author": "Martin Luther King Jr."},
	{"quote": "Real love stories never have endings.", "author": "Richard Bach"},
	{"quote": "Love is a smoke made with the fume of sighs.", "author": "William Shakespeare"},
	{"quote": "A hug is like a boomerang - you get it back right away.", "author": "Bil Keane"},
	{"quote": "Talk not of wasted affection; affection never was wasted.", "author": "Henry Wadsworth Longfellow"},
	{"quote": "Love does not begin and end the way we seem to think it does. Love is a battle, love is a war; love is a growing up.", "author": "James A. Baldwin"},
	{"quote": "Who, being loved, is poor?", "author": "Oscar Wilde"},
	{"quote": "It is difficult to know at what moment love begins; it is less difficult to know that it has begun.", "author": "Henry Wadsworth Longfellow"},
	{"quote": "Love conquers all.", "author": "Virgil"},
	{"quote": "You don't have to go looking for love when it's where you come from.", "author": "Werner Erhard"},
	{"quote": "Perfect love is rare indeed - for to be a lover will require that you continually have the subtlety of the very wise, the flexibility of the child, the sensitivity of the artist, the understanding of the philosopher, the acceptance of the saint, the tole", "author": "Rob Cella"},
	{"quote": "Love seems the swiftest, but it is the slowest of growths. No man or woman really knows what perfect love is until they have been married a quarter of a century.", "author": "Mark Twain"},
	{"quote": "Love at first sight is easy to understand; it's when two people have been looking at each other for a lifetime that it becomes a miracle.", "author": "Amy Bloom"},
	{"quote": "When I say I love Eastland, it sounds preposterous--a man who brutalizes people. But *you* love him or you wouldn't be here. You're going to Mississippi to create social change--and you love Eastland in your desire to create conditions which will redeem his children. Loving your enemy is manifest in putting your arms not around the man but around the social situation, to take power from those who misuse it--at which point they can become human too.", "author": "Bayard Rustin"},
	{"quote": "I would rather live and love where death is king than have eternal life where love is not.", "author": "Robert Green Ingersoll"},
	{"quote": "Take away love and our earth is a tomb.", "author": "Robert Browning"},
	{"quote": "Love, unrequited, robs me of my rest Love, hopeless love, my ardent soul encumbers Love, nightmare-like, lies heavy on my chest, And weaves itself into my midnight slumbers", "author": "William S. Gilbert"},
	{"quote": "Friendship often ends in love; but love in friendship - never.", "author": "Charles Caleb Colton"},
	{"quote": "Gravitation is not responsible for people falling in love.", "author": "Albert Einstein"},
	{"quote": "Sometimes it's hard to be a woman giving all your love to just one man.", "author": "Tammy Wynette"},
	{"quote": "Someday, after mastering the winds, the waves, the tides and gravity, we shall harness for God the energies of love, and then, for a second time in the history of the world, man will have discovered fire.", "author": "Pierre Teilhard de Chardin"},
	{"quote": "Love is the master key which opens the gates of happiness.", "author": "Oliver Wendell Holmes"},
	{"quote": "It happened once that a youth and a maiden beheld each other in a public assembly for the first time???The youth gazed with great delight upon the beautiful face until he caught the maiden???s eye???The mysterious communication that is established across a hous", "author": "Nan Fairbrother"},
	{"quote": "To a person in love, the value of the individual is intuitively known. Love needs no logic for its mission.", "author": "La Rochefoucauld"},
	{"quote": "When love is in excess it brings a man no honor nor worthiness.", "author": "Euripides"},
	{"quote": "I have found the paradox that if I love until it hurts, then there is no hurt, but only more love.", "author": "Mother Teresa"},
	{"quote": "Better to have loved and lost, than to have never loved at all.", "author": "Saint Augustine"},
	{"quote": "Love begets love, love knows no rules, this is the same for all.", "author": "Virgil"},
	{"quote": "Sex alleviates tension. Love causes it.", "author": "Woody Allen"},
	{"quote": "Absence makes the heart grow fonder.", "author": "Eleanor Roosevelt"},
	{"quote": "Love recieved and love given comprise the best form of therapy.", "author": "Gordon William Allport"},
	{"quote": "Pure love and suspicion cannot dwell together: at the door where the latter enters, the former makes its exit.", "author": "Alexandre Dumas"},
	{"quote": "In love there are things - bodies and words.", "author": "Joyce Carol Oates"},
	{"quote": "May your service of love a beautiful thing want nothing else, fear nothing else and let love be free to become what love truly is.", "author": "Hadewijch of Antwerp"},
	{"quote": "Love is the only force capable of transforming an enemy into friend.", "author": "Martin Luther King Jr."},
	{"quote": "Ever has it been that love knows not its own depth until the hour of separation.", "author": "Kahlil Gibran"},
	{"quote": "Absence diminishes mediocre passions and increases great ones, as the wind extinguishes candles and fans fires.", "author": "Francois de La Rochefoucauld"},
	{"quote": "When I write love songs, people think they're really soppy -- but I see love as a consolation for the boredom of life.", "author": "Martin Gore"},
	{"quote": "Try as you will, you cannot annihilate that eternal relic of the human heart, love.", "author": "Victor Hugo"},
	{"quote": "The hours I spend with you I look upon as sort of a perfumed garden, a dim twilight, and a fountain singing to it. You and you alone make me feel that I am alive. Other men it is said have seen angels, but I have seen thee and thou art enough.", "author": "George Moore"},
	{"quote": "Love is love's reward.", "author": "John Dryden"},
	{"quote": "Love does not dominate; it cultivates.", "author": "Johann Wolfgang von Goethe"},
	{"quote": "When love is not madness, it is not love.", "author": "Pedro Calderon de la Barca"},
	{"quote": "I was in love with loving.", "author": "Saint Augustine"},
	{"quote": "If you live to be a hundred, I want to live to be a hundred minus one day so I never have to live without you.", "author": "A. A. Milne"},
	{"quote": "Love is always bestowed as a gift - freely, willingly and without expectation. We don't love to be loved; we love to love.", "author": "Leo Buscaglia"},
	{"quote": "No deep and strong feeling, such as we may come across here and there in the world, is unmixed with compassion. The more we love, the more the object of our love seems to us to be a victim.", "author": "Boris Pasternak"},
	{"quote": "Since love grows within you, so beauty grows. For love is the beauty of the soul.", "author": "Saint Augustine"},
	{"quote": "Ace When you love someone, you've gotta trust them. There's no other way. You've got to give them the key to everything that's yours. Otherwise, what's the point And, for a while, I believed that's the kind of love I had.", "author": "Casino"},
	{"quote": "If you think there are no new frontiers, watch a boy ring the front doorbell on his first date.", "author": "Olin Miller"},
	{"quote": "Spread love everywhere you go. Let no one ever come to you without leaving happier.", "author": "Mother Teresa"},
	{"quote": "Love is repaid by love alone!", "author": "Mother Teresa"},
	{"quote": "I am certainly not an authority on love because there are no authorities on love, just those who've had luck with it and those who haven't.", "author": "Bill Cosby"},
	{"quote": "Are you ready to cut off your head and place your foot on it? If so, come; Love awaits you! Love is not grown in a garden, nor sold in the marketplace; whether you are a king or a servant, the price is your head, and nothing less. Yes, the cost of the el", "author": "James Baldwin"},
	{"quote": "Mortal lovers must not try to remain at the first step; for lasting passion is the dream of a harlot and from it we wake in despair.", "author": "C.S. Lewis"},
	{"quote": "Love can sometimes be magic. But magic can sometimes... just be an illusion.", "author": "Javan"},
	{"quote": "How absurd and delicious it is to be in love with somebody younger than yourself. Everybody should try it.", "author": "Barbara Pym"},
	{"quote": "The greatest happiness of life is the conviction that we are loved, loved for ourselves, or rather, loved in spite of ourselves.", "author": "Victor Hugo"},
	{"quote": "Hatred paralyzes life love releases it. Hatred confuses life love harmonizes it. Hatred darkens life love illumines it.", "author": "Martin Luther King, Jr."},
	{"quote": "Once the realization is accepted that even between the closest human beings infinite distances continue, a wonderful living side by side can grow, if they succeed in loving the distance between them which makes it possible for each to see the other whole against the sky.", "author": "Rainer Maria Rilke"},
	{"quote": "I love cats. I love their grace and their elegance. I love their independence and their arrogance, and the way they lie and look at you, summing you up, surely to your detriment, with that unnerving, unwinking, appraising stare.", "author": "Joyce Stranger"},
	{"quote": "Love sought is good, but given unsought is better.", "author": "William Shakespeare"},
	{"quote": "My wife is as handsome as when she was a girl, and I...fell in love with her; and what is more, I have never fallen out.", "author": "Abraham Lincoln"},
	{"quote": "Bitterness imprisons life love releases it. Bitterness paralyzes life love empowers it. Bitterness sours life love sweetens it. Bitterness sickens life love heals it. Bitterness blinds life love anoints its eyes.", "author": "Harry Emerson Fosdick"},
	{"quote": "We always believe our first love is our last, and our last love our first.", "author": "George John Whyte-Melville"},
	{"quote": "Immature love says: 'I love you because I need you.' Mature love says: 'I need you because I love you.'", "author": "Erich Fromm"},
	{"quote": "You have to walk carefully in the beginning of love; the running across fields into your lover's arms can only come later, when you're sure they won't laugh if you trip.", "author": "Jonathan Carroll"},
	{"quote": "Absence is to love as wind is to fire; It extinguishes the small and kindles the great.", "author": "Roger de Bussy-Rabutin"},
	{"quote": "Love makes your soul crawl out from its hiding place.", "author": "Zora Neale Hurston"},
	{"quote": "When women love us, they forgive us everything, even our crimes when they do not love us, they give us credit for nothing, not even our virtues.", "author": "Honore' de Balzac"},
	{"quote": "For small creatures such as we the vastness is bearable only through love.", "author": "Carl Sagan"},
	{"quote": "Loving a child doesn't mean giving in to all his whims to love him is to bring out the best in him, to teach him to love what is difficult.", "author": "Nadia Boulanger"},
	{"quote": "Love is an ideal thing, marriage a real thing; a confusion of the real with the ideal never goes unpunished.", "author": "Johann Wolfgang von Goethe"},
	{"quote": "Love is an irresistible desire to be irresistibly desired.", "author": "Robert Frost"},
	{"quote": "The greatest gift a parent can give a child is unconditional love. As a child wanders and strays, finding his bearings, he needs a sense of absolute love from a parent. There's nothing wrong with tough love, as long as the love is unconditional.", "author": "George Herbert Walker Bush"},
	{"quote": "Love is a sign from the heavens that you are here for a reason.", "author": "J. Ghetto"},
	{"quote": "The greatest pleasure of life is love.", "author": "William Temple"},
	{"quote": "The fickleness of the women I love is only equaled by the infernal constancy of the women who love me.", "author": "George Bernard Shaw"},
	{"quote": "Just because you love someone doesnt mean you have to be involved with them. Love is not a bandage to cover wounds.", "author": "Hugh Elliott"},
	{"quote": "A loving heart is the truest wisdom.", "author": "Charles Dickens"},
	{"quote": "Love is a fruit in season at all times, and within reach of every hand.", "author": "Mother Teresa"},
	{"quote": "Ama me fideliter! Fidem meam noto: De corde totaliter Et ex mente tota, Sum presentialiter Absens in remota.", "author": "Anon."},
	{"quote": "You cannot be lonely if you like the person you're alone with.", "author": "Wayne Dyer"},
	{"quote": "Nobody has ever measured, not even poets, how much the heart can hold.", "author": "Zelda Fitzgerald"},
	{"quote": "Young love is a flame; very pretty, often very hot and fierce, but still only light and flickering. The love of the older and disciplined heart is as coals, deep burning, unquenchable.", "author": "Henry Ward Beecher"},
	{"quote": "These flowers, which were splendid and sprightly, waking in the dawn of the morning, in the evening will be a pitiful frivolity, sleeping in the cold night's arms.", "author": "Pedro Calderon de la Barca"},
	{"quote": "Being deeply loved by someone gives you strength; loving someone deeply gives you courage.", "author": "Lao Tzu"},
	{"quote": "Love is only half the illusion the lover, but not his love, is deceived.", "author": "George Santayana"},
	{"quote": "Love is much nicer to be in than an automobile accident, a tight girdle, a higher tax bracket or a holding pattern over Philadelphia.", "author": "Judith Viorst"},
	{"quote": "How we glow over these novels of passion, when the story is told with any spark of truth and nature! And what fastens attention, in the intercourse of life, like any passage betraying affection between two parties? Perhaps we never saw them before and nev", "author": "Erich Fromm"},
	{"quote": "To fall in love is easy, even to remain in it is not difficult; our human loneliness is cause enough. But it is a hard quest worth making to find a comrade through whose steady presence one becomes steadily the person one desires to be.", "author": "Elijah Wood"},
	{"quote": "Come live with me, and be my love, And we will some new pleasures prove Of golden sands, and crystal brooks, With silken lines, and silver hooks.", "author": "TS (Thomas Stearns) Eliot"},

	{ "quote": "Hay amores tan bellos que justifican todas las locuras que hacen cometer.", "author": "Plutarco"},
	{ "quote": "El amor se compone de una sola alma que habita en dos cuerpos.", "author": "Aristóteles"},
	{ "quote": "Ofrecer amistad al que pide amor es como dar pan al que muere de sed.", "author": "Ovidio"},
	{ "quote": "El amor conquista todas las cosas. Démosle paso al amor.", "author": "Virgilio"},
	{ "quote": "Ama y haz lo que quieras. Si callas, callarás con amor; si gritas, gritarás con amor; si corriges, corregirás con amor, si perdonas, perdonarás con amor.", "author": "Tácito"},
	{ "quote": "El amor es intensidad y por esto es una distensión del tiempo: estira los minutos y los alarga como siglos.", "author": "Octavio Paz"},
	{ "quote": "En asuntos de amor, los locos son los que tienen más experiencia. De amor no preguntes nunca a los cuerdos; los cuerdos aman cuerdamente, que es como no haber amado nunca.", "author": "Jacinto Benavente"},
	{ "quote": "El verdadero amor no es el amor propio, es el que consigue que el amante se abra a las demás personas y a la vida; no atosiga, no aísla, no rechaza, no persigue: solamente acepta.", "author": "Antonio Gala"},
	{ "quote": "Hay quien ha venido al mundo para amar a una sola mujer y, consecuentemente, no es probable que tropiece con ella.", "author": "José Ortega y Gasset."},
	{ "quote": "Me estás enseñando a amar. Yo no sabía. Amar es no pedir, es dar. Mi alma, vacía.", "author": "Gerardo Diego"},
	{ "quote": "Por eso juzgo y discierno, por cosa cierta y notoria, que tiene el amor su gloria a las puertas del infierno.", "author": "Miguel de Cervantes"},
	{ "quote": "La raíz de todas las pasiones es el amor. De él nace la tristeza, el gozo, la alegría y la desesperación.", "author": "Lope de Vega"},
	{ "quote": "Solo hay algo más vacío que haber vivido sin amor y es haber vivido sin dolor.", "author": "Jo Nesbø"},
	{ "quote": "Temer al amor es temer a la vida, y los que temen a la vida ya están medio muertos.", "author": "Bertrand Russell"},
	{ "quote": "No ser amados es una simple desventura; la verdadera desgracia es no amar.", "author": "Albert Camus"},
	{ "quote": "El amor es el anhelo de salir de uno mismo.", "author": "Charles Baudelaire"},
	{ "quote": "Las cartas de amor se empiezan sin saber lo que se va a decir y se terminan sin saber lo que se ha dicho.", "author": "Jean-Jacques Rousseau"},
	{ "quote": "Hay que saber que no existe país sobre la tierra donde el amor no haya convertido a los amantes en poetas.", "author": "Voltaire"},
	{ "quote": "El amor es una maravillosa flor, pero es necesario tener el valor de ir a buscarla al borde de un horrible precipicio.", "author": "Stendhal"},
	{ "quote": "Amar no es mirarse el uno al otro; es mirar juntos en la misma dirección.", "author": "Antoine de Saint-Exupéry"},
	{ "quote": "Trata de amar al prójimo. Ya me dirás el resultado.", "author": "Jean-Paul Sartre"},
	{ "quote": "Ama un solo día y el mundo habrá cambiado.", "author": "Robert Browning"},
	{ "quote": "Sabes que estás enamorado cuando no quieres acostarte porque la realidad es por fin mejor que tus sueños.", "author": "Dr. Seuss"},
	{ "quote": "Dadme a mi Romeo, y cuando muera lleváoslo y divididlo en pequeñas estrellas. El rostro del cielo se tornará tan bello que el mundo entero se enamorará de la noche y dejará de adorar al estridente sol.", "author": "William Shakespeare"},
	{ "quote": "Soy lo que has hecho de mí. Toma mis elogios, toma mi culpa, toma todo el éxito, toma el fracaso, en resumen, tómame.", "author": "Charles Dickens"}
];
